// Fixed browser asset allowlist. No arbitrary resource paths are accepted.
#pragma once
#include <unordered_map>
#include <string>
namespace Shipmate {
inline const std::unordered_map<std::string, std::string> AssetPaths = {
    { "gEquippedItemOutlineTex", "__OTR__textures/parameter_static/gEquippedItemOutlineTex" },
    { "gLButtonTex", "__OTR__textures/icon_item_static/gLButtonTex" },
    { "gRButtonTex", "__OTR__textures/icon_item_static/gRButtonTex" },
    { "gAmmoDigit0Tex", "__OTR__textures/parameter_static/gAmmoDigit0Tex" },
    { "gAmmoDigit1Tex", "__OTR__textures/parameter_static/gAmmoDigit1Tex" },
    { "gAmmoDigit2Tex", "__OTR__textures/parameter_static/gAmmoDigit2Tex" },
    { "gAmmoDigit3Tex", "__OTR__textures/parameter_static/gAmmoDigit3Tex" },
    { "gAmmoDigit4Tex", "__OTR__textures/parameter_static/gAmmoDigit4Tex" },
    { "gAmmoDigit5Tex", "__OTR__textures/parameter_static/gAmmoDigit5Tex" },
    { "gAmmoDigit6Tex", "__OTR__textures/parameter_static/gAmmoDigit6Tex" },
    { "gAmmoDigit7Tex", "__OTR__textures/parameter_static/gAmmoDigit7Tex" },
    { "gAmmoDigit8Tex", "__OTR__textures/parameter_static/gAmmoDigit8Tex" },
    { "gAmmoDigit9Tex", "__OTR__textures/parameter_static/gAmmoDigit9Tex" },
    { "gPauseMenuCursorTopLeftTex", "__OTR__textures/icon_item_static/gPauseMenuCursorTopLeftTex" },
    { "gPauseMenuCursorTopRightTex", "__OTR__textures/icon_item_static/gPauseMenuCursorTopRightTex" },
    { "gPauseMenuCursorBottomLeftTex", "__OTR__textures/icon_item_static/gPauseMenuCursorBottomLeftTex" },
    { "gPauseMenuCursorBottomRightTex", "__OTR__textures/icon_item_static/gPauseMenuCursorBottomRightTex" },
    { "hud-button", "__OTR__textures/parameter_static/gButtonBackgroundTex" },
    { "hud-dpad", "__OTR__textures/parameter_static/gDPad" },
    { "hud-c-left", "__OTR__textures/parameter_static/gEmptyCLeftArrowTex" },
    { "hud-c-down", "__OTR__textures/parameter_static/gEmptyCDownArrowTex" },
    { "hud-c-right", "__OTR__textures/parameter_static/gEmptyCRightArrowTex" },
    { "gPauseSelectItem00ENGTex", "__OTR__textures/icon_item_nes_static/gPauseSelectItem00ENGTex" },
    { "gPauseSelectItem01Tex", "__OTR__textures/icon_item_static/gPauseSelectItem01Tex" },
    { "gPauseSelectItem02Tex", "__OTR__textures/icon_item_static/gPauseSelectItem02Tex" },
    { "gPauseSelectItem03Tex", "__OTR__textures/icon_item_static/gPauseSelectItem03Tex" },
    { "gPauseSelectItem04Tex", "__OTR__textures/icon_item_static/gPauseSelectItem04Tex" },
    { "gPauseSelectItem10ENGTex", "__OTR__textures/icon_item_nes_static/gPauseSelectItem10ENGTex" },
    { "gPauseSelectItem11Tex", "__OTR__textures/icon_item_static/gPauseSelectItem11Tex" },
    { "gPauseSelectItem12Tex", "__OTR__textures/icon_item_static/gPauseSelectItem12Tex" },
    { "gPauseSelectItem13Tex", "__OTR__textures/icon_item_static/gPauseSelectItem13Tex" },
    { "gPauseSelectItem14Tex", "__OTR__textures/icon_item_static/gPauseSelectItem14Tex" },
    { "gPauseSelectItem20ENGTex", "__OTR__textures/icon_item_nes_static/gPauseSelectItem20ENGTex" },
    { "gPauseSelectItem21Tex", "__OTR__textures/icon_item_static/gPauseSelectItem21Tex" },
    { "gPauseSelectItem22Tex", "__OTR__textures/icon_item_static/gPauseSelectItem22Tex" },
    { "gPauseSelectItem23Tex", "__OTR__textures/icon_item_static/gPauseSelectItem23Tex" },
    { "gPauseSelectItem24Tex", "__OTR__textures/icon_item_static/gPauseSelectItem24Tex" },
    { "gPauseEquipment00Tex", "__OTR__textures/icon_item_static/gPauseEquipment00Tex" },
    { "gPauseEquipment01Tex", "__OTR__textures/icon_item_static/gPauseEquipment01Tex" },
    { "gPauseEquipment02Tex", "__OTR__textures/icon_item_static/gPauseEquipment02Tex" },
    { "gPauseEquipment03Tex", "__OTR__textures/icon_item_static/gPauseEquipment03Tex" },
    { "gPauseEquipment04Tex", "__OTR__textures/icon_item_static/gPauseEquipment04Tex" },
    { "gPauseEquipment10ENGTex", "__OTR__textures/icon_item_nes_static/gPauseEquipment10ENGTex" },
    { "gPauseEquipment11Tex", "__OTR__textures/icon_item_static/gPauseEquipment11Tex" },
    { "gPauseEquipment12Tex", "__OTR__textures/icon_item_static/gPauseEquipment12Tex" },
    { "gPauseEquipment13Tex", "__OTR__textures/icon_item_static/gPauseEquipment13Tex" },
    { "gPauseEquipment14Tex", "__OTR__textures/icon_item_static/gPauseEquipment14Tex" },
    { "gPauseEquipment20Tex", "__OTR__textures/icon_item_static/gPauseEquipment20Tex" },
    { "gPauseEquipment21Tex", "__OTR__textures/icon_item_static/gPauseEquipment21Tex" },
    { "gPauseEquipment22Tex", "__OTR__textures/icon_item_static/gPauseEquipment22Tex" },
    { "gPauseEquipment23Tex", "__OTR__textures/icon_item_static/gPauseEquipment23Tex" },
    { "gPauseEquipment24Tex", "__OTR__textures/icon_item_static/gPauseEquipment24Tex" },
};
}
