// Fixed browser asset allowlist. No arbitrary resource paths are accepted.
#pragma once
#include <unordered_map>
#include <string>
namespace Shipmate {
inline const std::unordered_map<std::string, std::string> AssetPaths = {
    { "gEquippedItemOutlineTex", "textures/parameter_static/gEquippedItemOutlineTex" },
    { "gLButtonTex", "textures/icon_item_static/gLButtonTex" },
    { "gRButtonTex", "textures/icon_item_static/gRButtonTex" },
    { "gAmmoDigit0Tex", "textures/parameter_static/gAmmoDigit0Tex" },
    { "gAmmoDigit1Tex", "textures/parameter_static/gAmmoDigit1Tex" },
    { "gAmmoDigit2Tex", "textures/parameter_static/gAmmoDigit2Tex" },
    { "gAmmoDigit3Tex", "textures/parameter_static/gAmmoDigit3Tex" },
    { "gAmmoDigit4Tex", "textures/parameter_static/gAmmoDigit4Tex" },
    { "gAmmoDigit5Tex", "textures/parameter_static/gAmmoDigit5Tex" },
    { "gAmmoDigit6Tex", "textures/parameter_static/gAmmoDigit6Tex" },
    { "gAmmoDigit7Tex", "textures/parameter_static/gAmmoDigit7Tex" },
    { "gAmmoDigit8Tex", "textures/parameter_static/gAmmoDigit8Tex" },
    { "gAmmoDigit9Tex", "textures/parameter_static/gAmmoDigit9Tex" },
    { "gCounterDigit0Tex", "textures/parameter_static/gCounterDigit0Tex" },
    { "gCounterDigit1Tex", "textures/parameter_static/gCounterDigit1Tex" },
    { "gCounterDigit2Tex", "textures/parameter_static/gCounterDigit2Tex" },
    { "gCounterDigit3Tex", "textures/parameter_static/gCounterDigit3Tex" },
    { "gCounterDigit4Tex", "textures/parameter_static/gCounterDigit4Tex" },
    { "gCounterDigit5Tex", "textures/parameter_static/gCounterDigit5Tex" },
    { "gCounterDigit6Tex", "textures/parameter_static/gCounterDigit6Tex" },
    { "gCounterDigit7Tex", "textures/parameter_static/gCounterDigit7Tex" },
    { "gCounterDigit8Tex", "textures/parameter_static/gCounterDigit8Tex" },
    { "gCounterDigit9Tex", "textures/parameter_static/gCounterDigit9Tex" },
    { "gOcarinaBtnIconATex", "textures/parameter_static/gOcarinaBtnIconATex" },
    { "gOcarinaBtnIconCDownTex", "textures/parameter_static/gOcarinaBtnIconCDownTex" },
    { "gOcarinaBtnIconCRightTex", "textures/parameter_static/gOcarinaBtnIconCRightTex" },
    { "gOcarinaBtnIconCLeftTex", "textures/parameter_static/gOcarinaBtnIconCLeftTex" },
    { "gOcarinaBtnIconCUpTex", "textures/parameter_static/gOcarinaBtnIconCUpTex" },
    { "gPauseMenuCursorTopLeftTex", "textures/icon_item_static/gPauseMenuCursorTopLeftTex" },
    { "gPauseMenuCursorTopRightTex", "textures/icon_item_static/gPauseMenuCursorTopRightTex" },
    { "gPauseMenuCursorBottomLeftTex", "textures/icon_item_static/gPauseMenuCursorBottomLeftTex" },
    { "gPauseMenuCursorBottomRightTex", "textures/icon_item_static/gPauseMenuCursorBottomRightTex" },
    { "gHeartEmptyTex", "textures/parameter_static/gHeartEmptyTex" },
    { "gHeartQuarterTex", "textures/parameter_static/gHeartQuarterTex" },
    { "gHeartHalfTex", "textures/parameter_static/gHeartHalfTex" },
    { "gHeartThreeQuarterTex", "textures/parameter_static/gHeartThreeQuarterTex" },
    { "gHeartFullTex", "textures/parameter_static/gHeartFullTex" },
    { "gDefenseHeartEmptyTex", "textures/parameter_static/gDefenseHeartEmptyTex" },
    { "gDefenseHeartQuarterTex", "textures/parameter_static/gDefenseHeartQuarterTex" },
    { "gDefenseHeartHalfTex", "textures/parameter_static/gDefenseHeartHalfTex" },
    { "gDefenseHeartThreeQuarterTex", "textures/parameter_static/gDefenseHeartThreeQuarterTex" },
    { "gDefenseHeartFullTex", "textures/parameter_static/gDefenseHeartFullTex" },
    { "gMagicMeterEndTex", "textures/parameter_static/gMagicMeterEndTex" },
    { "gMagicMeterMidTex", "textures/parameter_static/gMagicMeterMidTex" },
    { "hud-button", "textures/parameter_static/gButtonBackgroundTex" },
    { "hud-dpad", "textures/parameter_static/gDPad" },
    { "hud-c-left", "textures/parameter_static/gEmptyCLeftArrowTex" },
    { "hud-c-down", "textures/parameter_static/gEmptyCDownArrowTex" },
    { "hud-c-right", "textures/parameter_static/gEmptyCRightArrowTex" },
};
}
